#:schema node_modules/wrangler/config-schema.json
name = "kitchencraft"
main = "dist/index.js"
compatibility_date = "2024-09-25"

assets = { directory = "./public" }

[define]
"process.env.REMIX_DEV_ORIGIN" = "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[vars]
ACTOR_KIT_HOST = "kitchencraft.jonathanrmumm.workers.dev"

[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[durable_objects.bindings]]
name = "USER"
class_name = "User"

[[migrations]]
tag = "v1"
new_classes = ["Remix", "Session"]

[[migrations]]
tag = "v2"
new_classes = ["User"]
deleted_classes = ["Session"]

[observability]
enabled = true
