#:schema node_modules/wrangler/config-schema.json
name = "kitchencraft"
main = "dist/index.js"
compatibility_date = "2024-09-25"

assets = { directory = "./public" }

[define]
"process.env.REMIX_DEV_ORIGIN" = "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[durable_objects.bindings]]
name = "SESSION"
class_name = "Session"

[[migrations]]
tag = "v1"
new_classes = ["Remix", "Session"]

[observability]
enabled = true
